import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '@/styles/globals.css';
import Header from '@/components/layouts/header/header';
import Footer from '@/components/layouts/footer/footer';

const roboto = Roboto({
    subsets: ['vietnamese'],
    weight: ['100', '300', '400', '500', '700', '900'],
    display: 'swap'
});

export const metadata: Metadata = {
    title: 'HỎI ĐÁP - TRA CỨU CHÍNH SÁCH KHCN',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="vi">
            <body className={`${roboto.className} antialiased`}>
                <Header />
                <div>{children}</div>
                <Footer />
            </body>
        </html>
    );
}
